apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spring-petclinic
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-petclinic
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/liswang89/opp-policy.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
